ALTER TABLE API_PROJECT ALTER COLUMN ID TYPE BIGINT;
ALTER TABLE API_PROJECT ALTER COLUMN IMAGE_ID TYPE BIGINT;

ALTER TABLE API_SKILL ALTER COLUMN ID TYPE BIGINT;
ALTER TABLE API_SKILL ALTER COLUMN IMAGE_ID TYPE BIGINT;

ALTER TABLE API_PROJECT_SKILL_MAP ALTER COLUMN PROJECT_ID TYPE BIGINT;
ALTER TABLE API_PROJECT_SKILL_MAP ALTER COLUMN SKILL_ID TYPE BIGINT;

ALTER TABLE API_IMAGE ALTER COLUMN ID TYPE BIGINT;

ALTER TABLE API_USER ALTER COLUMN ID TYPE BIGINT;

ALTER TABLE API_ROLE ALTER COLUMN ID TYPE BIGINT;

ALTER TABLE API_USER_ROLE_MAP ALTER COLUMN USER_ID TYPE BIGINT;
ALTER TABLE API_USER_ROLE_MAP ALTER COLUMN ROLE_ID TYPE BIGINT;
