ALTER TABLE API_IMAGE ADD COLUMN PROJECT_ID BIGINT CONSTRAINT FK_API_IMAGE_PROJECT_ID REFERENCES API_PROJECT(ID);
ALTER TABLE API_IMAGE ADD COLUMN SKILL_ID BIGINT CONSTRAINT FK_API_IMAGE_SKILL_ID REFERENCES API_SKILL(ID);

UPDATE API_IMAGE SET PROJECT_ID = (SELECT ID FROM API_PROJECT WHERE API_PROJECT.IMAGE_ID = API_IMAGE.ID);
UPDATE API_IMAGE SET SKILL_ID = (SELECT ID FROM API_SKILL WHERE API_SKILL.IMAGE_ID = API_IMAGE.ID) ;

ALTER TABLE API_PROJECT DROP COLUMN IMAGE_ID;
ALTER TABLE API_SKILL DROP COLUMN IMAGE_ID;

ALTER TABLE API_PROJECT ALTER COLUMN DESCRIPTION_FR DROP DEFAULT;
ALTER TABLE API_IMAGE ALTER COLUMN ALT_FR DROP DEFAULT;
