-- User

CREATE SEQUENCE IF NOT EXISTS API_USER_SEQUENCE START WITH 1 INCREMENT BY 1;

CREATE TABLE API_USER (
    ID         INT          NOT NULL PRIMARY KEY,
    USERNAME   VARCHAR(255) NOT NULL,
    FIRST_NAME VARCHAR(255) NOT NULL,
    LAST_NAME  VARCHAR(255) NOT NULL,
    PASSWORD   VARCHAR(255) NOT NULL
);

-- Role

CREATE SEQUENCE IF NOT EXISTS API_ROLE_SEQUENCE START WITH 1 INCREMENT BY 1;

CREATE TABLE API_ROLE (
    ID   INT          NOT NULL PRIMARY KEY,
    NAME VARCHAR(255) NOT NULL
);

-- User Role Map

CREATE TABLE API_USER_ROLE_MAP (
    USER_ID INT NOT NULL,
    ROLE_ID INT NOT NULL,
    PRIMARY KEY (ROLE_ID, USER_ID),
    FOREIGN KEY (USER_ID) REFERENCES API_USER (ID),
    FOREIGN KEY (ROLE_ID) REFERENCES API_ROLE (ID)
);

-- Image

CREATE SEQUENCE IF NOT EXISTS API_IMAGE_SEQUENCE START WITH 1 INCREMENT BY 1;

CREATE TABLE API_IMAGE (
    ID  INT          NOT NULL PRIMARY KEY,
    URL VARCHAR(255) NOT NULL,
    ALT VARCHAR(255) NOT NULL
);

-- Project

CREATE SEQUENCE IF NOT EXISTS API_PROJECT_SEQUENCE START WITH 1 INCREMENT BY 1;

CREATE TABLE API_PROJECT (
    ID            INT          NOT NULL PRIMARY KEY,
    TITLE         VARCHAR(255) NOT NULL,
    DESCRIPTION   VARCHAR(255) NOT NULL,
    CREATION_DATE DATE         NOT NULL,
    REPO_URL      VARCHAR(255) NOT NULL,
    DEMO_URL      VARCHAR(255) NOT NULL,
    FEATURED      BOOLEAN      NOT NULL,
    IMAGE_ID      INT,
    FOREIGN KEY (IMAGE_ID) REFERENCES API_IMAGE (ID)
);

-- Skill

CREATE SEQUENCE IF NOT EXISTS API_SKILL_SEQUENCE START WITH 1 INCREMENT BY 1;

CREATE TABLE API_SKILL (
    ID       INT          NOT NULL PRIMARY KEY,
    NAME     VARCHAR(255) NOT NULL,
    IMAGE_ID INT,
    FOREIGN KEY (IMAGE_ID) REFERENCES API_IMAGE (id)
);

-- Project Skill Map

CREATE TABLE API_PROJECT_SKILL_MAP (
    PROJECT_ID INT NOT NULL,
    SKILL_ID   INT NOT NULL,
    PRIMARY KEY (PROJECT_ID, SKILL_ID),
    FOREIGN KEY (PROJECT_ID) REFERENCES API_PROJECT (ID),
    FOREIGN KEY (SKILL_ID) REFERENCES API_SKILL (ID)
);
